name: Cypress End-to-end tests
on: push
env:
  URL_SERVER: ${{ secrets.URL_SERVER}}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --spec cypress/e2e/tests
          browser: chrome
