name: Cypress End-to-end tests
on: push
env:
  URL_SERVER: ${{ secrets.URL_SERVER}}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD}}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./
          command: npx cypress run --browser chrome --spec cypress/e2e/tests --headless
      - name: Generate HTML Report
        run: |
          npx mochawesome-merge ./cypress/reports/html/*.json > ./cypress/reports/html/report.json
          npx mochawesome-report-generator ./cypress/reports/html/report.json --reportTitle "Report"
        #          command: npx cypress run --browser chrome --spec cypress/e2e/tests && npx mochawesome-merge ./cypress/reports/html/*.json > ./cypress/reports/html/report.json && exit 0
        #          command: npx cypress run --browser chrome --spec cypress/e2e/tests && npx mochawesome-merge ./cypress/reports/html/*.json > ./cypress/reports/html/report.json && npx mochawesome-report-generator ./cypress/reports/html/report.json --reportTitle "Report" || exit 0
        #          command: timeout 2m npx cypress run --browser chrome --spec cypress/e2e/tests || exit 0
        #          command: npx cypress run --browser chrome --spec cypress/e2e/tests --reporter cypress-mochawesome-reporter --reporter-options charts=true,reportPageTitle=cypress-client,embeddedScreenshots=true,inlineAssets=true,saveAllAttempts=false,autoOpen=true
      #          run: |
      #            timeout 2m npx cypress run --browser chrome --spec cypress/e2e/tests || exit 0
      #      - name: Generate HTML Report
      #        run: |
      #          echo "Start generate report process"
      #          npx mochawesome-merge ./cypress/reports/html/*.json > ./cypress/reports/html/report.json
      #          npx marge ./cypress/reports/html/report.json --reportDir ./cypress/reports/html --reportTitle "Cypress Report"
      #          echo "HTML report generated"
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Report
          path: ./cypress/reports/html
