name: Cypress End-to-end tests
on: push
env:
  URL_SERVER: ${{ secrets.URL_SERVER}}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD}}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --spec cypress/e2e/tests
#      - name: Report
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: Report
#          path: ./cypress/reports/html
